### ISSUE TITLE
Invoke-RestMethod : {"error":{"message":[""]}}

### ISSUE THREAD

**Issue by HerzScheisse-zz** [hdurdle/sureflap#1]
Hi,

First thank you for these ps scripts... its working fine... except for the 2 files where i get error messages...
Is it just me? Any tips on how to resolve these?

I have PowerShell running on a RasPi2 Raspbian image...
And i also want to mention, that i have 2 pets in my household, just in case this is maybe related to...

```
PS /etc/openhab2/scripts/sureflap> ./Get-SureFlapPetLocation.ps1

id          : 10431
name        : EddyMurphy
share_code  : xxxxx
timezone_id : 320
version     : NQ==
created_at  : 19.09.18 16:51:46
updated_at  : 28.12.18 17:41:25
timezone    : @{id=320; name=(UTC+02:00) Europe/Berlin; timezone=Europe/Berlin; utc_offset=7200; created_at=03.08.17 10:35:34; updated_at=03.08.17
              10:37:15}
users       : {@{id=xxxx; owner=True; write=True; version=MQ==; created_at=19.09.18 16:51:46; updated_at=19.09.18 16:51:47}}

Invoke-RestMethod : {"error":{"message":[""]}}
At /etc/openhab2/scripts/sureflap/Get-SureFlapPetLocation.ps1:19 char:8
+ $res = Invoke-RestMethod -Method Get -Uri $uri -Headers $headers -Con ...
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Method: GET, Re...repetcare.io
}:HttpRequestMessage) [Invoke-RestMethod], HttpResponseException
+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
Outside
```

```
PS /etc/openhab2/scripts/sureflap> ./Get-SureFlapUser.ps1
Invoke-RestMethod : {"error":{"message":[""]}}
At /etc/openhab2/scripts/sureflap/Get-SureFlapUser.ps1:19 char:8
+ $res = Invoke-RestMethod -Method Get -Uri $uri -Headers $headers -Con ...
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Method: GET, Re...rShell/6.2.0
}:HttpRequestMessage) [Invoke-RestMethod], HttpResponseException
+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
```

any Help will be much appreciated...

Thank You!

**Comment by hdurdle** [comment]
Hi - if you take a look at those scripts you'll see they both take parameters.  The scripts don't do any checking to see if the parameters are missing so die if they're not provided.

You need to pass the ID of a pet to this:

`.\Get-SureFlapPetLocation.ps1 <ID_of_Pet>`

and either the household ID, or the ID of a user to:

```
.\Get-SureFlapUser.ps1 -householdID <householdID>
.\Get-SureFlapUser.ps1 -userID <userID>
```

If you wanted to fix them up to do some input checking that'd be great!

(Oh, and having multiple pets is fine - this works with my lot, and I have 14 cats!)

**Comment by HerzScheisse-zz** [comment]
Hey,

> You need to pass the ID of a pet to this

Okay yeah I see it now and its working... thanks for the hint... :)

> (Oh, and having multiple pets is fine - this works with my lot, and I have 14 cats!)

Okay wow... thats nice... :)

> If you wanted to fix them up to do some input checking that'd be great!

I'm not very familiar with PS so i fear i cant fix it on my own... but actually no need for that... maybe update the Readme is just fine...

Thanks for your work
