### ISSUE TITLE
SetPetLocation do not work anymore

### ISSUE THREAD

**Issue by andreas0087** [hdurdle/sureflap#2]
Hi Guys,

I used your scrips often in the past - they are working very smoothly, thank you very much!
But today I have an issue:
I want to set a petlocation and using the script "Set-SureFlapPetPosition". The Pet-ID is 13756.

```
param (
	[string]$petID,
	[string]$where = 1 #  1 = inside (default), 2 = outside
)
# usage: .\Set-SureFlapPetPosition.ps1 pet_id [where]

. ./Get-SureFlapHousehold.ps1

$uri = $endpoint + "/pet/13756/position"

$headers = @{}
$headers.Add("Authorization","Bearer $token" ) | Out-Null

$postParams = @{
 "where" = "1"
 "since" = (Get-Date -format "2018-07-02T15:50:00+00:00")
} | ConvertTo-Json

$postParams

$res = Invoke-RestMethod -Method Post -Uri $uri -Headers $headers -Body $postParams -ContentType "application/json"
$res.data
```

After running this script, I get the following error message:

```
Invoke-RestMethod : {"error":{"message":[""]}}
In C:\Users\Andi\Documents\Dokumente\Katzen\Katzenklappe\API\PowerShell\Set-SureFlapPetPosition.ps1:21 Zeichen:8
+ $res = Invoke-RestMethod -Method Post -Uri $uri -Headers $headers -Bo ...
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

```

I do not know, what's the reason why the script do not work anymore. It would be really great if someone could help me to find a solution.

Thanks.

Best regards,
Andreas

**Comment by hdurdle** [comment]
You should just run the command without editing the file at all.  Using the stock file in the repo, run:

`.\Set-SureFlapPetPosition.ps1 13756 1`

(I just tried this on mine, and it works.)

You've directly edited the file, including the `$uri` so I'm not sure what the resulting behaviour would be.  Call the files and pass parameters, no need to edit the files themselves unless you need to change the behaviour.

**Comment by andreas0087** [comment]
Hi,

thanks for your feedback.
I downloaded the files again, entered my credentials in "SureFlapConfig-dist.ps1", run the "Get-SureFlapToken.ps1", entered the pet-id and where-id in "Set-SureFlapPetPosition.ps1" and run the file, but I'm stillgetting an error:


[Set-SureFlapPetPosition.zip](https://github.com/hdurdle/sureflap/files/4016746/Set-SureFlapPetPosition.zip)


```
Invoke-RestMethod : Ungültiger URI: Der Hostname konnte nicht analysiert werden.
In C:\Users\Andi\Desktop\sureflap-master\Set-SureFlapPetPosition.ps1:21 Zeichen:8
+ $res = Invoke-RestMethod -Method Post -Uri $uri -Headers $headers -Bo ...
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-RestMethod], UriFormatException
    + FullyQualifiedErrorId : System.UriFormatException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand


```

**Comment by hdurdle** [comment]
Remember you need to copy `SureFlapConfig-dist.ps1` to `SureFlapConfig.ps1` with your details, don't just edit the distribution file.

**Comment by hdurdle** [comment]
Also, the script does no error checking, so if you fail to provide a pet ID on the command line it will fail to run.

**Comment by andreas0087** [comment]
Ok, I've downloaded all files again.
Then i copied the file "SureFlapConfig-dist.ps1" and renamed the copy to "SureFlapConfig.ps1". Then I type in my e-mail adress and passwort, run the script "Get-SureFlapToken.ps1" to get the token and then i opened the file "Set-SureFlapPetPosition.ps1" and type in the Pet-ID (13756 - that's the existing Pet ID) and where (1), entered the desired since-date and run the script. But I'm still getting an error:

```
Invoke-RestMethod : {"error":{"message":[""]}}
In C:\Users\Andi\Desktop\sureflap-master\Set-SureFlapPetPosition.ps1:21 Zeichen:8
+ $res = Invoke-RestMethod -Method Post -Uri $uri -Headers $headers -Bo ...
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

```

I've ziped my whole file ordner (with deleted credentials):  
[sureflap-master.zip](https://github.com/hdurdle/sureflap/files/4018341/sureflap-master.zip)

**Comment by andreas0087** [comment]
Hi,

I

**Comment by andreas0087** [comment]
Ok, I've downloaded all files again and now it works. Sorry for the confusion and thank you very much for your support!
